/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdsRouteImport } from './routes/_authenticated/ads'
import { Route as AuthenticatedBestiesRouteImport } from './routes/_authenticated/besties'
import { Route as AuthenticatedDmRouteImport } from './routes/_authenticated/dm'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedFeedsRouteImport } from './routes/_authenticated/feeds'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedMemoriesRouteImport } from './routes/_authenticated/memories'
import { Route as AuthenticatedPagesRouteImport } from './routes/_authenticated/pages'
import { Route as AuthenticatedReelsRouteImport } from './routes/_authenticated/reels'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedSavedProductsRouteImport } from './routes/_authenticated/saved-products'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDmUserIdRouteImport } from './routes/_authenticated/dm.$userId'
import { Route as AuthenticatedPostIdRouteImport } from './routes/_authenticated/post.$id'
import { Route as AuthenticatedProfileUsernameRouteImport } from './routes/_authenticated/profile.$username'
import { Route as AuthenticatedStoryUsernameRouteImport } from './routes/_authenticated/story.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdsRoute = AuthenticatedAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBestiesRoute = AuthenticatedBestiesRouteImport.update({
  id: '/besties',
  path: '/besties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDmRoute = AuthenticatedDmRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedsRoute = AuthenticatedFeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoriesRoute = AuthenticatedMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagesRoute = AuthenticatedPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReelsRoute = AuthenticatedReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedProductsRoute =
  AuthenticatedSavedProductsRouteImport.update({
    id: '/saved-products',
    path: '/saved-products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDmUserIdRoute = AuthenticatedDmUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AuthenticatedDmRoute,
} as any)
const AuthenticatedPostIdRoute = AuthenticatedPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileUsernameRoute =
  AuthenticatedProfileUsernameRouteImport.update({
    id: '/profile/$username',
    path: '/profile/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoryUsernameRoute =
  AuthenticatedStoryUsernameRouteImport.update({
    id: '/story/$username',
    path: '/story/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ads': typeof AuthenticatedAdsRoute
  '/besties': typeof AuthenticatedBestiesRoute
  '/dm': typeof AuthenticatedDmRouteWithChildren
  '/events': typeof AuthenticatedEventsRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/feeds': typeof AuthenticatedFeedsRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/memories': typeof AuthenticatedMemoriesRoute
  '/pages': typeof AuthenticatedPagesRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/saved-products': typeof AuthenticatedSavedProductsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/dm/$userId': typeof AuthenticatedDmUserIdRoute
  '/post/$id': typeof AuthenticatedPostIdRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/story/$username': typeof AuthenticatedStoryUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ads': typeof AuthenticatedAdsRoute
  '/besties': typeof AuthenticatedBestiesRoute
  '/dm': typeof AuthenticatedDmRouteWithChildren
  '/events': typeof AuthenticatedEventsRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/feeds': typeof AuthenticatedFeedsRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/memories': typeof AuthenticatedMemoriesRoute
  '/pages': typeof AuthenticatedPagesRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/saved-products': typeof AuthenticatedSavedProductsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/dm/$userId': typeof AuthenticatedDmUserIdRoute
  '/post/$id': typeof AuthenticatedPostIdRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/story/$username': typeof AuthenticatedStoryUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ads': typeof AuthenticatedAdsRoute
  '/_authenticated/besties': typeof AuthenticatedBestiesRoute
  '/_authenticated/dm': typeof AuthenticatedDmRouteWithChildren
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/feeds': typeof AuthenticatedFeedsRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/memories': typeof AuthenticatedMemoriesRoute
  '/_authenticated/pages': typeof AuthenticatedPagesRoute
  '/_authenticated/reels': typeof AuthenticatedReelsRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/saved-products': typeof AuthenticatedSavedProductsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/dm/$userId': typeof AuthenticatedDmUserIdRoute
  '/_authenticated/post/$id': typeof AuthenticatedPostIdRoute
  '/_authenticated/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/_authenticated/story/$username': typeof AuthenticatedStoryUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ads'
    | '/besties'
    | '/dm'
    | '/events'
    | '/explore'
    | '/feed'
    | '/feeds'
    | '/friends'
    | '/groups'
    | '/history'
    | '/memories'
    | '/pages'
    | '/reels'
    | '/saved'
    | '/saved-products'
    | '/settings'
    | '/dm/$userId'
    | '/post/$id'
    | '/profile/$username'
    | '/story/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ads'
    | '/besties'
    | '/dm'
    | '/events'
    | '/explore'
    | '/feed'
    | '/feeds'
    | '/friends'
    | '/groups'
    | '/history'
    | '/memories'
    | '/pages'
    | '/reels'
    | '/saved'
    | '/saved-products'
    | '/settings'
    | '/dm/$userId'
    | '/post/$id'
    | '/profile/$username'
    | '/story/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ads'
    | '/_authenticated/besties'
    | '/_authenticated/dm'
    | '/_authenticated/events'
    | '/_authenticated/explore'
    | '/_authenticated/feed'
    | '/_authenticated/feeds'
    | '/_authenticated/friends'
    | '/_authenticated/groups'
    | '/_authenticated/history'
    | '/_authenticated/memories'
    | '/_authenticated/pages'
    | '/_authenticated/reels'
    | '/_authenticated/saved'
    | '/_authenticated/saved-products'
    | '/_authenticated/settings'
    | '/_authenticated/dm/$userId'
    | '/_authenticated/post/$id'
    | '/_authenticated/profile/$username'
    | '/_authenticated/story/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ads': {
      id: '/_authenticated/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AuthenticatedAdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/besties': {
      id: '/_authenticated/besties'
      path: '/besties'
      fullPath: '/besties'
      preLoaderRoute: typeof AuthenticatedBestiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dm': {
      id: '/_authenticated/dm'
      path: '/dm'
      fullPath: '/dm'
      preLoaderRoute: typeof AuthenticatedDmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feeds': {
      id: '/_authenticated/feeds'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof AuthenticatedFeedsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memories': {
      id: '/_authenticated/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof AuthenticatedMemoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pages': {
      id: '/_authenticated/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof AuthenticatedPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reels': {
      id: '/_authenticated/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AuthenticatedReelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved-products': {
      id: '/_authenticated/saved-products'
      path: '/saved-products'
      fullPath: '/saved-products'
      preLoaderRoute: typeof AuthenticatedSavedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dm/$userId': {
      id: '/_authenticated/dm/$userId'
      path: '/$userId'
      fullPath: '/dm/$userId'
      preLoaderRoute: typeof AuthenticatedDmUserIdRouteImport
      parentRoute: typeof AuthenticatedDmRoute
    }
    '/_authenticated/post/$id': {
      id: '/_authenticated/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof AuthenticatedPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/$username': {
      id: '/_authenticated/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AuthenticatedProfileUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/story/$username': {
      id: '/_authenticated/story/$username'
      path: '/story/$username'
      fullPath: '/story/$username'
      preLoaderRoute: typeof AuthenticatedStoryUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedDmRouteChildren {
  AuthenticatedDmUserIdRoute: typeof AuthenticatedDmUserIdRoute
}

const AuthenticatedDmRouteChildren: AuthenticatedDmRouteChildren = {
  AuthenticatedDmUserIdRoute: AuthenticatedDmUserIdRoute,
}

const AuthenticatedDmRouteWithChildren = AuthenticatedDmRoute._addFileChildren(
  AuthenticatedDmRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdsRoute: typeof AuthenticatedAdsRoute
  AuthenticatedBestiesRoute: typeof AuthenticatedBestiesRoute
  AuthenticatedDmRoute: typeof AuthenticatedDmRouteWithChildren
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedFeedsRoute: typeof AuthenticatedFeedsRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMemoriesRoute: typeof AuthenticatedMemoriesRoute
  AuthenticatedPagesRoute: typeof AuthenticatedPagesRoute
  AuthenticatedReelsRoute: typeof AuthenticatedReelsRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSavedProductsRoute: typeof AuthenticatedSavedProductsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedPostIdRoute: typeof AuthenticatedPostIdRoute
  AuthenticatedProfileUsernameRoute: typeof AuthenticatedProfileUsernameRoute
  AuthenticatedStoryUsernameRoute: typeof AuthenticatedStoryUsernameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdsRoute: AuthenticatedAdsRoute,
  AuthenticatedBestiesRoute: AuthenticatedBestiesRoute,
  AuthenticatedDmRoute: AuthenticatedDmRouteWithChildren,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedFeedsRoute: AuthenticatedFeedsRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMemoriesRoute: AuthenticatedMemoriesRoute,
  AuthenticatedPagesRoute: AuthenticatedPagesRoute,
  AuthenticatedReelsRoute: AuthenticatedReelsRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSavedProductsRoute: AuthenticatedSavedProductsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedPostIdRoute: AuthenticatedPostIdRoute,
  AuthenticatedProfileUsernameRoute: AuthenticatedProfileUsernameRoute,
  AuthenticatedStoryUsernameRoute: AuthenticatedStoryUsernameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
